## numpy知识点

In [63]:
import numpy as np
np.__version__

'1.24.3'

### 创建数组

In [64]:
# 创建数组
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [65]:
# 查看类型
a.dtype

dtype('int32')

In [66]:
b = np.array([1.2, 2.3, 3.4])
b.dtype

dtype('float64')

In [67]:
# 转换多维数组
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
# 生成2×3的全0数组
np.zeros((2, 3))

# 生成3×4的全1数组
np.ones((3, 4), dtype=np.int16)

# 生成2×3未初始化的随机数数组
np.empty([2, 3])

# arange方法用于创建给定范围内的数组
np.arange(10, 30, 5)

array([10, 15, 20, 25])

随机数
- rand方法用于生成符合(0,1)均匀分布的随机数数组
- randint方法用于生成指定范围内固定长度的整数数组
- randn用于生成符合标准正态分布的随机数数组

In [69]:
np.random.rand(3,2)

array([[0.90425789, 0.43212937],
       [0.69378173, 0.62693778],
       [0.12211495, 0.89406287]])

In [70]:
np.random.randint(3,size=5)

array([1, 2, 1, 0, 2])

### 数组的索引与切片

In [71]:
# 一维数组索引
a = np.arange(10)**2
a[2]
a[1:4]
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [72]:
b = np.random.random((3,3))
b

array([[0.80030339, 0.11693454, 0.93679286],
       [0.5993018 , 0.31600583, 0.17010398],
       [0.11630448, 0.30027634, 0.02513427]])

In [73]:
b[1,2]

0.1701039780332788

In [74]:
b[:,1]

array([0.11693454, 0.31600583, 0.30027634])

### 数组运算
- 基本运算
- 线性代数

In [75]:
a = np.arange(4)
b = np.array([5,10,15,20])
b-a

array([ 5,  9, 13, 17])

In [76]:
b**2

array([ 25, 100, 225, 400])

In [77]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [78]:
b<20

array([ True,  True,  True, False])

In [79]:
np.mean(b)

12.5

In [80]:
np.var(b)

31.25

In [81]:
np.median(b)

12.5

In [82]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A,B

(array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]]))

In [83]:
A*B

array([[2, 0],
       [0, 4]])

In [84]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [85]:
np.linalg.inv(A) # 逆

array([[ 1., -1.],
       [ 0.,  1.]])

In [86]:
np.linalg.det(A) # 行列式

1.0

### 维度变换

In [87]:
a = np.floor(10*np.random.random((3,4)))
a

array([[3., 4., 0., 9.],
       [0., 6., 9., 5.],
       [6., 4., 7., 4.]])

In [88]:
a.shape

(3, 4)

In [89]:
a.ravel() # 数组展平

array([3., 4., 0., 9., 0., 6., 9., 5., 6., 4., 7., 4.])

In [90]:
a.T

array([[3., 0., 6.],
       [4., 6., 4.],
       [0., 9., 7.],
       [9., 5., 4.]])

In [91]:
a.T.shape

(4, 3)

In [92]:
a.reshape(3,-1)

array([[3., 4., 0., 9.],
       [0., 6., 9., 5.],
       [6., 4., 7., 4.]])

### 合并切分

In [98]:
A,B

(array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]]))

In [93]:
np.hstack((A,B))

array([[1, 1, 2, 0],
       [0, 1, 3, 4]])

In [94]:
np.vstack((A,B))

array([[1, 1],
       [0, 1],
       [2, 0],
       [3, 4]])

In [95]:
C = np.arange(16.0).reshape(4,4)

In [96]:
np.hsplit(C,2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [97]:
np.vsplit(C,2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]